#pragma once

#include "commands/commands.h"

//who are you
#define CLIENT_WHO_ARE_YOU_COMMAND_RESP_FAIL_1S GENEATATE_FAIL_FMT(SERVER_WHO_ARE_YOU_COMMAND, "%s")
#define CLIENT_WHO_ARE_YOU_COMMAND_RESP_SUCCSESS_1S GENEATATE_SUCCESS_FMT(SERVER_WHO_ARE_YOU_COMMAND, "%s")

//http
#define CLIENT_PLEASE_CONNECT_HTTP_COMMAND_RESP_FAIL_1S GENEATATE_FAIL_FMT(SERVER_PLEASE_CONNECT_HTTP_COMMAND, "%s")
#define CLIENT_PLEASE_CONNECT_HTTP_COMMAND_RESP_SUCCSESS_1S GENEATATE_SUCCESS_FMT(SERVER_PLEASE_CONNECT_HTTP_COMMAND, "%s")

#define CLIENT_PLEASE_DISCONNECT_HTTP_COMMAND_RESP_FAIL GENEATATE_FAIL_FMT(SERVER_PLEASE_DISCONNECT_HTTP_COMMAND, "")
#define CLIENT_PLEASE_DISCONNECT_HTTP_COMMAND_RESP_SUCCSESS GENEATATE_SUCCESS_FMT(SERVER_PLEASE_DISCONNECT_HTTP_COMMAND, "")

// websocket
#define CLIENT_PLEASE_CONNECT_WEBSOCKET_COMMAND_RESP_FAIL_1S GENEATATE_FAIL_FMT(SERVER_PLEASE_CONNECT_WEBSOCKET_COMMAND, "%s")
#define CLIENT_PLEASE_CONNECT_WEBSOCKET_COMMAND_RESP_SUCCSESS_1S GENEATATE_SUCCESS_FMT(SERVER_PLEASE_CONNECT_WEBSOCKET_COMMAND, "%s")

#define CLIENT_PLEASE_DISCONNECT_WEBSOCKET_COMMAND_RESP_FAIL GENEATATE_FAIL_FMT(SERVER_PLEASE_DISCONNECT_WEBSOCKET_COMMAND, "")
#define CLIENT_PLEASE_DISCONNECT_WEBSOCKET_COMMAND_RESP_SUCCSESS GENEATATE_SUCCESS_FMT(SERVER_PLEASE_DISCONNECT_WEBSOCKET_COMMAND, "")

// system info
#define CLIENT_PLEASE_SYSTEM_INFO_COMMAND_RESP_FAIL_1S GENEATATE_FAIL_FMT(SERVER_PLEASE_SYSTEM_INFO_COMMAND, "%s")
#define CLIENT_PLEASE_SYSTEM_INFO_COMMAND_RESP_SUCCSESS_1J GENEATATE_SUCCESS_FMT(SERVER_PLEASE_SYSTEM_INFO_COMMAND, "'%s'")

// config
#define CLIENT_PLEASE_CONFIG_COMMAND_RESP_FAIL_1S GENEATATE_FAIL_FMT(SERVER_PLEASE_CONFIG_COMMAND, "%s")
#define CLIENT_PLEASE_CONFIG_COMMAND_RESP_SUCCSESS_1J GENEATATE_SUCCESS_FMT(SERVER_PLEASE_CONFIG_COMMAND, "'%s'")

namespace fasto
{
    namespace siteonyourdevice
    {
    }
}
