#pragma once

#include "commands/commands.h"

#define CLIENT_WHO_ARE_YOU_COMMAND_RESP_FAIL_1S GENEATATE_FAIL_FMT(SERVER_WHO_ARE_YOU_COMMAND, "%s")
#define CLIENT_WHO_ARE_YOU_COMMAND_RESP_SUCCSESS_1S GENEATATE_SUCCESS_FMT(SERVER_WHO_ARE_YOU_COMMAND, "%s")

#define CLIENT_PLEASE_CONNECT_COMMAND_RESP_FAIL_1S GENEATATE_FAIL_FMT(SERVER_PLEASE_CONNECT_RELAY_COMMAND, "%s")
#define CLIENT_PLEASE_CONNECT_COMMAND_RESP_SUCCSESS_1S GENEATATE_SUCCESS_FMT(SERVER_PLEASE_CONNECT_RELAY_COMMAND, "%s")

#define CLIENT_PLEASE_DISCONNECT_COMMAND_RESP_FAIL GENEATATE_FAIL_FMT(SERVER_PLEASE_DISCONNECT_COMMAND, "")
#define CLIENT_PLEASE_DISCONNECT_COMMAND_RESP_SUCCSESS GENEATATE_SUCCESS_FMT(SERVER_PLEASE_DISCONNECT_COMMAND, "")

#define CLIENT_PLEASE_SYSTEM_INFO_COMMAND_RESP_FAIL_1S GENEATATE_FAIL_FMT(SERVER_PLEASE_SYSTEM_INFO_COMMAND, "%s")
#define CLIENT_PLEASE_SYSTEM_INFO_COMMAND_RESP_SUCCSESS_1J GENEATATE_SUCCESS_FMT(SERVER_PLEASE_SYSTEM_INFO_COMMAND, "'%s'")

namespace fasto
{
    namespace siteonyourdevice
    {
    }
}
